name: drug-nme

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - pip
  - pip:
      - pandas
      - tqdm
      - tabula-py
      - JPype1
      - matplotlib
      - seaborn
      - legendkit
      - hypothesis
      - pytest
      - notebook
